// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFDRN.Server.Database;

#nullable disable

namespace SFDRN.Server.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260224122049_InitialProfileStorage")]
    partial class InitialProfileStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SFDRN.Server.Database.Models.StoredMessage", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FromNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("StoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ttl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.HasKey("MessageId");

                    b.HasIndex("StoredAt")
                        .HasDatabaseName("IX_Messages_StoredAt");

                    b.HasIndex("ToNodeId", "DeliveredAt")
                        .HasDatabaseName("IX_Messages_Recipient_Delivered");

                    b.HasIndex("ToNodeId", "Timestamp")
                        .HasDatabaseName("IX_Messages_Recipient_Timestamp");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SFDRN.Server.Database.Models.StoredProfile", b =>
                {
                    b.Property<string>("NodeId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalNickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Hey! I'm using SFDRN");

                    b.HasKey("NodeId");

                    b.HasIndex("GlobalNickname")
                        .HasDatabaseName("IX_Profiles_GlobalNickname");

                    b.HasIndex("Hash")
                        .HasDatabaseName("IX_Profiles_Hash");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("IX_Profiles_LastSeenAt");

                    b.HasIndex("LastUpdated")
                        .HasDatabaseName("IX_Profiles_LastUpdated");

                    b.ToTable("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
